version: '3'
services:
  calculator:
    build:
      context: "logic/"
      dockerfile: "Dockerfile"
  frontend:
    image: "webdevtoolsandtech/currency-frontend"
  backend:
    image: "webdevtoolsandtech/currency-backend"
    environment:
      - REDIS_ADDRESS=redis-db:6379
      - SESSION_SECRET=5EBE2294ECD0E0F08EAB7690D2A6EE69
      - USER_SERVICE_ADDRESS=user-service:80
      - FRONTEND_ADDRESS=frontend:80
      - CALCULATOR_ADDRESS=calculator:5000
    ports:
      - "8080:80"
    depends_on:
      - redis-db
      - calculator
      - user-service
      - frontend
  redis-db:
    image: "redis:alpine"
  user-service:
    image: "webdevtoolsandtech/user-service"
    environment:
      - REDIS_ADDRESS=redis-db:6379
    depends_on:
      - redis-db
  e2e-test:
    depends_on:
      - backend
    build:
      context: "e2e/"
      dockerfile: "Dockerfile"




